services:
  # --- NEW: Gateway Service (Application Entry Point) ---
  gateway:
    build: ./Gateway # Path to the Gateway service's Dockerfile
    container_name: gateway_service
    restart: on-failure
    ports:
      - "8080:8080" # This is the main port you will access your application from
    environment:
      - SERVER_PORT=8080
      # URLs for the downstream services that the gateway will route to
      - IAM_SERVICE_URL=http://iam:8082
      - LOGREADER_SERVICE_URL=http://logreader:8081
      - NOTIFICATION_SERVICE_URL=http://notification:8083
    networks:
      - my-app-network

  # --- IAM Service and its Database ---
  db-iam:
    image: postgres:16-alpine
    container_name: iam_postgres_db
    restart: always
    environment:
      POSTGRES_DB: iamdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - iam-db-data:/var/lib/postgresql/data
    networks:
      - my-app-network

  iam:
    build: ./IAM
    container_name: iam_service
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-iam:5432/iamdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db-iam
    networks:
      - my-app-network

  # --- logReader Service and its Database ---
  db-logreader:
    image: postgres:16-alpine
    container_name: logreader_postgres_db
    restart: always
    environment:
      POSTGRES_DB: pagerDuty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7525
    ports:
      - "5433:5432"
    volumes:
      - logreader-db-data:/var/lib/postgresql/data
    networks:
      - my-app-network

  logreader:
    build: ./logReader
    container_name: logreader_service
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-logreader:5432/pagerDuty
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=7525
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=logger
      - NOTIFICATION_SERVICE_URL=http://notification:8083
    depends_on:
      - db-logreader
    networks:
      - my-app-network

  # --- Notification Service ---
  notification:
    build: ./Notification
    container_name: notification_service
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
    networks:
      - my-app-network

# Define the network for all services
networks:
  my-app-network:
    driver: bridge

# Define the named volumes for data persistence
volumes:
  iam-db-data:
  logreader-db-data: